import React from 'react';
import { Rink } from '../types';

interface PrintScorecardViewProps {
  rinks: Rink[];
  playerCount: number;
  dateStr: string;
}

export const PrintScorecardView: React.FC<PrintScorecardViewProps> = ({
  rinks,
  playerCount,
  dateStr
}) => {
  if (!rinks || rinks.length === 0) return null;

  return (
    <div className="hidden print:block text-black bg-white p-6 max-w-5xl mx-auto">
      {/* Printable Sheet Header */}
      <div className="border-b-2 border-black pb-4 mb-6 flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-black uppercase tracking-wide">
            Lawn Bowls Rink Draw — Triples
          </h1>
          <p className="text-sm font-semibold text-neutral-800">
            Official Club Match Sheet • {playerCount} Bowlers ({rinks.length} {rinks.length === 1 ? 'Rink' : 'Rinks'})
          </p>
        </div>
        <div className="text-right text-xs font-mono">
          <p>Date: {dateStr}</p>
          <p>Format: Triples (3 bowls / 2 bowls)</p>
        </div>
      </div>

      {/* Grid of Rinks for Noticeboard */}
      <div className="grid grid-cols-2 gap-6">
        {rinks.map((rink) => (
          <div
            key={rink.id}
            className="border-2 border-black rounded-lg p-3 page-break-avoid"
          >
            <div className="bg-neutral-200 border-b-2 border-black -mx-3 -mt-3 p-2 flex justify-between items-center mb-3">
              <span className="font-black text-lg">RINK {rink.rinkNumber}</span>
              <span className="text-xs font-bold uppercase tracking-wider">
                Triples Match
              </span>
            </div>

            <div className="grid grid-cols-2 gap-3 text-xs">
              {/* Red Team */}
              <div className="border border-neutral-400 rounded p-2">
                <div className="font-black text-xs uppercase border-b border-neutral-300 pb-1 mb-1.5 flex justify-between">
                  <span>RED (Mat End 1)</span>
                  <span>Score: ___</span>
                </div>
                <div className="space-y-1">
                  <div>
                    <span className="font-semibold text-[10px] text-neutral-600 block">SKIP:</span>
                    <span className="font-bold text-sm">{rink.teamA.skip.name}</span>
                  </div>
                  <div>
                    <span className="font-semibold text-[10px] text-neutral-600 block">SECOND:</span>
                    <span className="font-bold text-sm">{rink.teamA.second.name}</span>
                  </div>
                  <div>
                    <span className="font-semibold text-[10px] text-neutral-600 block">LEAD:</span>
                    <span className="font-bold text-sm">{rink.teamA.lead.name}</span>
                  </div>
                </div>
              </div>

              {/* Blue Team */}
              <div className="border border-neutral-400 rounded p-2">
                <div className="font-black text-xs uppercase border-b border-neutral-300 pb-1 mb-1.5 flex justify-between">
                  <span>BLUE TEAM</span>
                  <span>Score: ___</span>
                </div>
                <div className="space-y-1">
                  <div>
                    <span className="font-semibold text-[10px] text-neutral-600 block">SKIP:</span>
                    <span className="font-bold text-sm">{rink.teamB.skip.name}</span>
                  </div>
                  <div>
                    <span className="font-semibold text-[10px] text-neutral-600 block">SECOND:</span>
                    <span className="font-bold text-sm">{rink.teamB.second.name}</span>
                  </div>
                  <div>
                    <span className="font-semibold text-[10px] text-neutral-600 block">LEAD:</span>
                    <span className="font-bold text-sm">{rink.teamB.lead.name}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Scorecard row for writing ends */}
            <div className="mt-3 pt-2 border-t border-dashed border-neutral-400 flex justify-between text-[11px] font-mono">
              <span>Ends Played: [  ]</span>
              <span>Winner: [ RED / BLUE ]</span>
              <span>Signature: ________________</span>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-8 pt-4 border-t border-neutral-300 text-center text-xs text-neutral-600 font-mono">
        Generated by Lawn Bowls Draw App • Please return completed scorecards to the match secretary.
      </div>
    </div>
  );
};
